version: "3"
services:
  app:
    image: awesometic/h5ai
    volumes:
      - ./shared:/h5ai
      # - ./config:/config
    ports:
      - 80:80
    environment:
      TZ: "Asia/Istanbul"
    #   PUID: "${UID}"
    #   PGID: "${GID}"
    restart: unless-stopped
# Docker NFS mount
# volumes:
#   data_volume:
#     driver_opts:
#       type: "nfs"
#       o: "addr=192.168.1.2,nolock,soft,rw"
#       device: ":/disk1/data"
