version: "3"
services:

  db:
    image: mariadb:10.5.6-focal
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-allowed-packet=64MB
    environment:
      MYSQL_DATABASE: matomo
      MYSQL_ROOT_PASSWORD: matomo
      MYSQL_USER: matomo
      MYSQL_PASSWORD: matomo
    volumes:
      - ./data/db:/var/lib/mysql
    restart: unless-stopped

  app:
    image: matomo:3.14.1-apache
    environment:
      MATOMO_DATABASE_HOST: "db"
      MATOMO_DATABASE_USERNAME: "matomo"
      MATOMO_DATABASE_PASSWORD: "matomo"
      MATOMO_DATABASE_DBNAME: "matomo"
    ports:
      - 8080:80
    volumes:
      - ./data/matomo:/var/www/html
    restart: unless-stopped
