version: "3"
services:

  cassandra:
    image: bitnami/cassandra:3-debian-10
    container_name: cassandra
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - ./data:/bitnami
    environment:
      CASSANDRA_PASSWORD: "cassandra"
      CASSANDRA_SEEDS: "cassandra"
      CASSANDRA_PASSWORD_SEEDER: "yes"
