version: "3.6"
services:

  node-exporter:
    image: prom/node-exporter:latest
    hostname: ${HOSTNAME}
    container_name: node-exporter
    user: root
    privileged: true
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.ntp'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
