version: "3"
services:

  registry:
    image: registry:2
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml:ro
      - ./data:/var/lib/registry
      # - registry_volume:/var/lib/registry
    ports:
      - "5000:5000"
    restart: unless-stopped

# Docker NFS mount
# volumes:
#   registry_volume:
#     driver_opts:
#       type: "nfs"
#       o: "addr=192.168.1.2,nolock,soft,rw"
#       device: ":/disk1/docker-registry-mirror"
